import catchAsyncError from "./catchAsyncError.js";


 export const isAthenticated = catchAsyncError(async(req, res, next) => {

})